
GET http://localhost:3333/users

###
GET http://localhost:3333/users/3923bca3-38f8-44ee-abcd-3d12ef118c19

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "teste",
    "email": "tesrt@gmail.com"
}
